FROM node:16-alpine3.15 AS builder

ENV VITE_API_URL=https://myapp-api-366321-d4jd4xerya-uc.a.run.app

WORKDIR /app

COPY ./apps/front/package*.json /app/

RUN npm ci

COPY ./apps/front /app/

RUN npm run build

CMD ["npm","run", "preview"]
