FROM node:16-alpine3.15

ENV API_PORT 8080 
ENV HOST 0.0.0.0

WORKDIR /app

RUN npm install -g @nestjs/cli 

COPY ./apps/api/package*.json /app/

RUN npm ci

COPY ./apps/api /app/

RUN npm run build

CMD ["npm", "run", "start:prod"]