FROM node:16-alpine3.15 as production

WORKDIR /app

RUN npm install -g @nestjs/cli 

COPY ./apps/api/package*.json /app/

RUN npm ci

COPY ./apps/api /app/

RUN npm run build

CMD ["npm", "run", "start:prod"]