name: Docker

on:
  push:
    branches: [ main ]

jobs:

    deploy-front:

        name: Deploy myApp-front on GCloud
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID_FRONT }}/${{ secrets.GCP_APP_NAME_FRONT }}
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID_FRONT }}
            service_account_email: ${{ secrets.GCP_EMAIL_FRONT }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS_FRONT }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME -f apps/front/Dockerfile.production .

        - name: Test Docker image
          run: docker run $IMAGE_NAME sh -c "npm test -v"

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID_FRONT }} --image $IMAGE_NAME --region us-central1 --platform managed